version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      #- run:
      #    name: "Say hello"
      #    command: "echo Hello, World!"
      - run:
          name: "Check PR Title"
          command: |
            #!/bin/bash
            # Extract the branch name from the environment variable
            BRANCH_NAME=$CIRCLE_BRANCH
            
            # Check if the branch name starts with the required pattern
            if [[ $BRANCH_NAME =~ ^SCP-[0-9]{4} ]]; then
              echo "Branch name '$BRANCH_NAME' is valid."
            else
              echo "Branch name '$BRANCH_NAME' is invalid. It must start with 'SCP-' followed by 4 digits."
              exit 1
            fi
            

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              ignore:
                - main
