version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      #- run:
      #    name: "Say hello"
      #    command: "echo Hello, World!"
      - run:
          name: "Check PR Title"
          command: |
            #!/bin/bash
            # Extract PR number from the CIRCLE_PULL_REQUEST URL
            echo $CIRCLE_BRANCH
            

workflows:
  say-hello-workflow:
    jobs:
      - say-hello:
          filters:
            branches:
              ignore:
                - main
